return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   enabled = false,
  --   dependencies = { "jose-elias-alvarez/typescript.nvim" },
  --   opts = {
  --     servers = {
  --       tsserver = {
  --         settings = {
  --           typescript = {
  --             inlayHints = {
  --               includeInlayEnumMemberValueHints = false,
  --               includeInlayFunctionLikeReturnTypeHints = false,
  --               includeInlayFunctionParameterTypeHints = false,
  --               includeInlayParameterNameHints = "all",
  --               includeInlayParameterNameHintsWhenArgumentMatchesName = false, -- false
  --               includeInlayPropertyDeclarationTypeHints = false,
  --               includeInlayVariableTypeHints = false,
  --               includeInlayVariableTypeHintsWhenTypeMatchesName = false, -- false
  --             },
  --           },
  --           javascript = {
  --             inlayHints = {
  --               includeInlayEnumMemberValueHints = false,
  --               includeInlayFunctionLikeReturnTypeHints = false,
  --               includeInlayFunctionParameterTypeHints = false,
  --               includeInlayParameterNameHints = "all",
  --               includeInlayParameterNameHintsWhenArgumentMatchesName = false,
  --               includeInlayPropertyDeclarationTypeHints = false,
  --               includeInlayVariableTypeHints = false,
  --               includeInlayVariableTypeHintsWhenTypeMatchesName = false,
  --             },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
